### ISSUE TITLE
mpvue课程更新 | 蜗牛老湿的个人网站

### ISSUE THREAD

**Issue by shengxinjing** [shengxinjing/my_blog#19]
http://shengxinjing.cn/books/mpvue-update.html

**Comment by GongJS** [comment]
666

**Comment by Been101** [comment]
老师，有一个问题，就是我调用这个方法时，老是报错说
![image](https://user-images.githubusercontent.com/24450293/46680470-c53b9600-cc1b-11e8-90a2-1c341af7e20b.png)
`qcloud.loginWithCode({
success: res => {
// qcloud.Session.set({ userInfo: res, logged: true })
this.loginSuccess(res)
console.log('登录成功')

},
fail: err => {
console.error(err, 222)
console.log('登录错误', err.message)
}
})`
可是我刚调用qclound.login() 方法登录啊。老师能给个思路吗

**Comment by yzq739291773** [comment]
为什么按照你的这个新的登录思路写，还是报错，最后我直接贴你的源码，也还是报错，
{"code":-1,"error":"ERR_GET_SESSION_KEY\n{\"code\":0,\"message\":\"\",\"codeDesc\":\"Success\",\"data\":{\"errcode\":40029,\"errmsg\":\"invalid code, hints: [ req_id: Gjws9a02642034 ]\"}}"}，好苦恼啊，老师，指点一下

**Comment by yzq739291773** [comment]
关键是我这样改了后，同样没有授权弹窗
