### ISSUE TITLE
github桌面软件使用教程

### ISSUE THREAD

**Issue by shengxinjing** [shengxinjing/my_blog#4]
### 首先　要先安装 [桌面版官网](https://desktop.github.com/)，或者百度搜github windows下载即可

可以再github网站上直接点击，把代码添加的桌面软件中

![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur00.png)

也可以再左上角添加项目，比如actual_07_homework，如果没有，说明还没有权限，联系我开通

![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur01.png)
![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur02.png)

---

项目初始化之后，写代码，修改文件之后，窗口内会看到修改的内容

![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur03.png)

输入提交的信息，点击commit

![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur04.png)

commit完之后，代码改动保存在了本地，点击一下右上角的sync 即可同步到github上，如果别人对代码有修改，你点一下sync，就可以把最新的代码同步到本地
![](http://7xjoq9.com1.z0.glb.clouddn.com/github-tur05.png)

最后
![](http://7xjoq9.com1.z0.glb.clouddn.com/github-turstar.png)

如果您觉得有我写的东西对你帮助，可以打赏点钱给我支付宝支持我，谢谢

![](http://7xjoq9.com1.z0.glb.clouddn.com/zhifubao.png)

**Comment by seerjk** [comment]
:+1:

**Comment by zrdsj** [comment]
受教了，还是很有用
